# Generated by Django 3.1 on 2020-09-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Symbol to look up the currency on e.g. Google', max_length=16)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=4, help_text='Value of 1 unit of the currency in EUR', max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency.currency')),
            ],
            options={
                'ordering': ('currency', 'date'),
            },
        ),
    ]
